Feature/12 add rails admin config
BrightCoders-Institute/proyecto-final-ror-team1 pull request #14
Opened 2023-08-03 03:07 UTC by Alonso2105

# Description

What did you implemented/Why did you implemented this:

- Explain the changes you’ve made.
- It doesn’t need to be fancy and you don’t have to get to technical, yet.
- Just explicit what you have implemented at a high level.
- Let the reviewer know the overall effect of the PR.
- Reference a ticket in your issue tracker. Explain what the change is and then and only then reference the ticket.
- The “why” is a chance to explain both the engineering goal, but also a some business objective that is satisfied or moved along.

Examples:

- What?: I've added support for authentication to implement Key Result 2 of OKR1. It includes
model, table, controller and test. For more background, see ticket #JIRA-123.
- Why?: These changes complete the user login and account creation experience. See #JIRA-123 for more information.

## Testing

Help me how can I test or look at the changes

 Example:

- I've added coverage for testing all new methods. I used Faker for a few random user emails and names.

## Screenshots

If applicable, include screenshots of the results or screenshots that help to see changes

2023-08-03 23:53 UTC, JuanequeX requested changes

2023-08-03 23:53 UTC, JuanequeX commented on shipments_tracker/config/initializers/rails_admin.rb
> +  # end
if this code is unnecessary please remove it

2023-08-03 23:53 UTC, JuanequeX commented on shipments_tracker/config/initializers/rails_admin.rb
> +      # end
remove this comment code

2023-08-03 23:53 UTC, JuanequeX commented on shipments_tracker/config/importmap.rails_admin.rb
> +pin "jquery-ui/", to: "https://ga.jspm.io/npm:jquery-ui@1.13.2/"
add a line at the end of this file

2023-08-03 23:53 UTC, JuanequeX commented on shipments_tracker/bin/dev
> +exec foreman start -f Procfile.dev "$@"
FIY: in my current project we have this configuration and the performance running it with `bin/dev` is excellent, this is only a suggestion, if it is useful for you apply it, if not forget about it
```
#!/usr/bin/env sh
OVERMIND_SKIP_ENV=1
export OVERMIND_SKIP_ENV

PORT="${PORT:-3000}"
export PORT

if command -v overmind > /dev/null 2>&1; then
  exec overmind start -f Procfile.dev "$@"
else
  echo "Installing foreman..."
  gem install foreman
  exec foreman start -f Procfile.dev "$@"
fi
```

2023-08-04 16:14 UTC, Alonso2105 commented on shipments_tracker/config/importmap.rails_admin.rb
> +pin "jquery-ui/", to: "https://ga.jspm.io/npm:jquery-ui@1.13.2/"
It's done

2023-08-05 01:25 UTC, JuanequeX approved these changes

2023-08-05 01:28 UTC, merged