Tailwind view of shipment index
BrightCoders-Institute/proyecto-final-ror-team1 pull request #43
Opened 2023-09-05 00:42 UTC by VaGar91

# Description
I implemented the styled view for shipments/index

## Testing
rails s

## Screenshots
<img width="1512" alt="Captura de pantalla 2023-09-04 a la(s) 18 41 04" src="https://github.com/BrightCoders-Institute/proyecto-final-ror-team1/assets/98784339/b2420db5-7217-45f4-b3b7-42cae96b8282">

2023-09-05 17:04 UTC, JuanequeX requested changes

2023-09-05 17:04 UTC, JuanequeX commented on app/views/shipments/index.html.erb
> +        <td></td>
if this `<td>` does not accomplish any purpose, please delete it.

2023-09-05 23:52 UTC, VaGar91 commented on app/views/shipments/index.html.erb
> +        <td></td>
done

2023-09-06 02:00 UTC, JuanequeX approved these changes

2023-09-06 23:02 UTC, Manz1999 approved these changes

2023-09-06 23:20 UTC, merged